version: "3.9"

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgresql
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - db:/var/lib/postgresql/data postgres
    ports:
      - "5436:5432"

volumes:
  db:

